name: Check linting

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build setup
        run: |
          rustup component add rustfmt
          rustup component add clippy
      - name: lint check
        run: |
          cargo fmt --check
          cargo clippy --no-deps --all-features --release -- -Dwarnings
